name: .NET Core Test and Publish

on:
  push:
    branches: [master]
  pull_request:

env:
  DOTNET_VERSION: 8.0.x
  DOTNET_TEST_PARAMETERS: --no-build /p:CollectCoverage=true -l "console;verbosity=detailed"
  COVERLET_EXCLUDE_COVERAGE: /p:Exclude=\"[EpicChain.SmartContract.TestEngine]*,[EpicChain.Compiler.CSharp.UnitTests]*,[Neo]*,[EpicChain.IO]*,[EpicChain.Json]*,[EpicChain.VM]*,[EpicChain.Extensions]*,[EpicChain.Cryptography.BLS12_381]*\"
  COVERLET_OUTPUT: /p:CoverletOutput=${{ github.workspace }}/coverage-join/
  COVERLET_MERGE_WITH: /p:MergeWith=${{ github.workspace }}/coverage-join/coverage.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Check format
      run: |
        dotnet format --no-restore --verify-no-changes --verbosity diagnostic
    - name: Build EpicChain.Compiler.CSharp
      run: dotnet build ./src/EpicChain.Compiler.CSharp/EpicChain.Compiler.CSharp.csproj
    - name: Build EpicChain.SmartContract.Template and test templates
      run: |
        dotnet pack ./src/EpicChain.SmartContract.Template/EpicChain.SmartContract.Template.csproj --configuration Debug
        dotnet new install ./src/EpicChain.SmartContract.Template/bin/Debug/EpicChain.SmartContract.Template.*.nupkg
        dotnet new epicchaincontractxep17 -n Xep17Contract -o ./src/EpicChain.SmartContract.Template/bin/Debug/xep17/ --force
        dotnet new epicchaincontractowner -n Ownable -o ./src/EpicChain.SmartContract.Template/bin/Debug/ownable/ --force
        dotnet new neocontractoracle -n OracleRequest -o ./src/EpicChain.SmartContract.Template/bin/Debug/oracle/ --force
        dotnet new uninstall EpicChain.SmartContract.Template
        dotnet remove ./src/EpicChain.SmartContract.Template/bin/Debug/xep17/Xep17Contract.csproj package EpicChain.SmartContract.Framework
        dotnet add    ./src/EpicChain.SmartContract.Template/bin/Debug/xep17/Xep17Contract.csproj reference ./src/EpicChain.SmartContract.Framework/EpicChain.SmartContract.Framework.csproj
        dotnet remove ./src/EpicChain.SmartContract.Template/bin/Debug/ownable/Ownable.csproj package EpicChain.SmartContract.Framework
        dotnet add    ./src/EpicChain.SmartContract.Template/bin/Debug/ownable/Ownable.csproj reference ./src/EpicChain.SmartContract.Framework/EpicChain.SmartContract.Framework.csproj
        dotnet remove ./src/EpicChain.SmartContract.Template/bin/Debug/oracle/OracleRequest.csproj package EpicChain.SmartContract.Framework
        dotnet add    ./src/EpicChain.SmartContract.Template/bin/Debug/oracle/OracleRequest.csproj reference ./src/EpicChain.SmartContract.Framework/EpicChain.SmartContract.Framework.csproj
        dotnet ./src/EpicChain.Compiler.CSharp/bin/Debug/netEpicChain.SmartContractc/EpicChain.SmartContract.Template/bin/Debug/xep17/Xep17ContractEpicChain.SmartContracts/EpicChain.SmartContract.Template.UnitTests/templates/epicchaincontractxep17/Artifacts/
        dotnet ./src/EpicChain.Compiler.CSharp/bin/Debug/netEpicChain.SmartContractc/EpicChain.SmartContract.Template/bin/Debug/ownable/OwnableEpicChain.SmartContracts/EpicChain.SmartContract.Template.UnitTests/templates/epicchaincontractowner/Artifacts/
        dotnet ./src/EpicChain.Compiler.CSharp/bin/Debug/netEpicChain.SmartContractc/EpicChain.SmartContract.Template/bin/Debug/oracle/OracleRequestEpicChain.SmartContracts/EpicChain.SmartContract.Template.UnitTests/templates/neocontractoracle/Artifacts/
    - name: Build Solution
      run: dotnet build ./epicchain-devkit-dotnet.sln
    - name: Add package coverlet.msbuild
      run: find tests -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
    - name: Test EpicChain.Compiler.CSharp.UnitTests
      run: |
        dotnet test ./tests/EpicChain.Compiler.CSharp.UnitTests \
        ${{ env.DOTNET_TEST_PARAMETERS }} \
        ${{ env.COVERLET_OUTPUT }} \
        ${{ env.COVERLET_EXCLUDE_COVERAGE }} \
    - name: Test EpicChain.SmartContract.Framework.UnitTests
      run: |
        dotnet test ./tests/EpicChain.SmartContract.Framework.UnitTests \
        ${{ env.DOTNET_TEST_PARAMETERS }} \
        ${{ env.COVERLET_OUTPUT }} \
        ${{ env.COVERLET_MERGE_WITH }} \
        ${{ env.COVERLET_EXCLUDE_COVERAGE }} \
    - name: Test EpicChain.SmartContract.Testing.UnitTests
      run: |
        dotnet test ./tests/EpicChain.SmartContract.Testing.UnitTests \
        ${{ env.DOTNET_TEST_PARAMETERS }} \
        ${{ env.COVERLET_OUTPUT }} \
        ${{ env.COVERLET_MERGE_WITH }} \
        ${{ env.COVERLET_EXCLUDE_COVERAGE }} \
    - name: Test EpicChain.SmartContract.Template.UnitTests
      run: |
        dotnet test ./tests/EpicChain.SmartContract.Template.UnitTests \
        ${{ env.DOTNET_TEST_PARAMETERS }} \
        ${{ env.COVERLET_MERGE_WITH }} \
        ${{ env.COVERLET_EXCLUDE_COVERAGE }} \
        /p:CoverletOutput=${{ github.workspace }}/coverage/lcov \
        /p:CoverletOutputFormat=lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: lcov
        file: ${{ github.workspace }}/coverage/lcov.info

  PublishPackage:
    if: github.ref == 'refs/heads/master' && startsWith(github.repository, 'neo-project/')
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set Version (dev-pack)
      run: git rev-list --count HEAD | xargs printf 'CI%05d' | xargs -I{} echo 'VERSION_SUFFIX={}' >> $GITHUB_ENV
    - name: Set Version (EpicChain)
      run: |
        git --git-dir=./neo/.git rev-list --count HEAD | xargs printf 'CI%05d' | xargs -I{} echo 'VERSION_SUFFIX_NEO={}' >> $GITHUB_ENV
        sed -n 's/.*<VersionPrefix>\(.*\)<\/VersionPrefix>.*/\1/p' ./neo/src/Directory.Build.props | xargs -I{} echo 'VERSION_NEO={}' >> $GITHUB_ENV

    - name : Pack (EpicChain.SmartContract.Framework)
      run: |
        dotnet pack ./src/EpicChain.SmartContract.Framework \
        --configuration Debug \
        --output ./out \
        --version-suffix ${{ env.VERSION_SUFFIX }}
    - name : Replace EpicChain reference by package in EpicChain.SmartContract.Testing
      run: |
        dotnet remove ./src/EpicChain.SmartContract.Testing/EpicChain.SmartContract.Testing.csproj reference '..\..\epicchain\src\EpicChain\EpicChain.csproj'
        dotnet add    ./src/EpicChain.SmartContract.Testing/EpicChain.SmartContract.Testing.csproj package 'Neo' --version ${{ env.VERSION_NEO }}-${{ env.VERSION_SUFFIX_NEO }}
    - name : Build (EpicChain.SmartContract.Testing)
      run: |
        dotnet build ./src/EpicChain.SmartContract.Testing -f net8.0
        dotnet build ./src/EpicChain.SmartContract.Testing -f netstandard2.1
    - name : Pack (EpicChain.SmartContract.Testing)
      run: |
        dotnet pack ./src/EpicChain.SmartContract.Testing \
        --no-build \
        --configuration Debug \
        --output ./out \
        --version-suffix ${{ env.VERSION_SUFFIX }}
    - name: Publish to Github Packages
      working-directory: ./out
      run: |
        dotnet nuget push * \
            --source https://nuget.pkg.github.com/epicchainlabs/index.json \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --disable-buffering \
            --no-service-endpoint;
    - name: Publish to myGet
      working-directory: ./out
      run: |
        dotnet nuget push * \
            --source https://www.myget.org/F/neo/api/v3/index.json \
            --api-key "${{ secrets.MYGET_TOKEN }}" \
            --disable-buffering \
            --no-service-endpoint;

  Release:
    if: github.ref == 'refs/heads/master' && startsWith(github.repository, 'neo-project/')
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Get version
      id: get_version
      run: |
        sudo apt install xmlstarlet
        find src -name Directory.Build.props | xargs xmlstarlet sel -N i=http://schemas.microsoft.com/developer/msbuild/2003 -t -v "concat('::set-output name=version::v',//i:VersionPrefix/text())" | xargs echo
    - name: Check tag
      id: check_tag
      run: curl -s -I ${{ format('https://github.com/{0}/releases/tag/{1}', github.repository, steps.get_version.outputs.version) }} | head -n 1 | cut -d$' ' -f2 | xargs printf "::set-output name=statusCode::%s" | xargs echo
    - name: Create release
      if: steps.check_tag.outputs.statusCode == '404'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: ${{ steps.get_version.outputs.version }}
        prerelease: ${{ contains(steps.get_version.outputs.version, '-') }}
    - name: Setup .NET Core
      if: steps.check_tag.outputs.statusCode == '404'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Publish to NuGet
      if: steps.check_tag.outputs.statusCode == '404'
      run: |
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain/EpicChain.csproj
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain.Cryptography.BLS12_381/EpicChain.Cryptography.BLS12_381.csproj
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain.Extensions/EpicChain.Extensions.csproj
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain.IO/EpicChain.IO.csproj
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain.Json/EpicChain.Json.csproj
        dotnet sln epicchain-devkit-dotnet.sln remove ./epicchain/src/EpicChain.VM/EpicChain.VM.csproj
        dotnet pack -o pub -c Release
        dotnet nuget push "pub/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN} --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
